name: BL-data-visualization-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - bokeh
  - plotly
  - plotnine
  - holoviews
  - datashader
  - keplergl
  - cufflinks
  - tabpy
